FROM node:19-alpine

ARG DB_NAME
ARG DB_USER
ARG DB_PASSWORD
ARG DB_HOST
ARG DB_PORT
ARG PORT

# Set environment variables during the build process
ENV DB_NAME=$DB_NAME
ENV DB_USER=$DB_USER
ENV DB_PASSWORD=$DB_PASSWORD
ENV DB_HOST=$DB_HOST
ENV DB_PORT=$DB_PORT
ENV PORT=$PORT

WORKDIR /app
COPY . .
RUN npm install
EXPOSE 3000

CMD ["npm","start" ]
